### ISSUE TITLE
Double // causes some warnings/trouble

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#36] opened 2019-11-28 23:36 UTC
·[33mFile path //miniconda/envs/umccrise/lib/python3.7/site-packages/ngs_utils/reference_data/key_genes/umccr_cancer_genes.GRCh37.coding.bed contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.·[0m 
·[33mFile path //miniconda/envs/umccrise/lib/python3.7/site-packages/ngs_utils/reference_data/key_genes/umccr_cancer_genes.GRCh37.coding.bed contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.·[0m

**Comment by brainstorm** [comment] 2019-12-19 01:51
Vlad, that `.replace()` on commit https://github.com/vladsaveliev/NGS_Utils/commit/f64e8ed6615998ef67456c7ce60be5c4919edbbd does not seem to tackle the root cause, I'm seeing it again elsewhere:

```  
Traceback (most recent call last): 
    File "//miniconda/envs/umccrise/lib/python3.7/site.py", line 168, in addpackage 
      exec(line) 
    File "<string>", line 1, in <module> 
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec 
  AttributeError: 'NoneType' object has no attribute 'loader' 
```

Do you know where that double `//` stems from? Reopening.

**Comment by vladsaveliev** [comment] 2019-12-20 04:45
Why do you think it has to do with `//`? The double `//` comes from miniconda in `install.sh` being installed into the current working directory, i.e. `$PWD/miniconda/` in bash. In docker, the current working directory is just root, i.e. `/`, so `$PWD/miniconda/` translates into `//miniconda/` inside of docker. But why do you think the error is caused by `//`? Looks like some issues with dynamic loading of matplotlib to me, but it doesn't seem to affect the run as far as I understand, though would be good to chase.

**Comment by brainstorm** [comment] 2019-12-20 05:57
I'm not saying that the error above is caused by `//`, I'm just saying that the "defect" is there and it only got fixed in one place with `.replace` (when it was an error and not just cosmetic).

It might have some side effects with i.e docker-slim scanning paths and not translating them well, for instance or any other downstream side effect that we are not anticipating yet. Just defensive programming.

**Comment by vladsaveliev** [comment] 2019-12-20 07:10
Agree, makes sense!

**Comment by pdiakumis** [comment] 2020-11-20 13:16
I.. am closing this since it doesn't seem to affect anything. Agree that warnings are annoying though.

**Closed by pdiakumis** 2020-11-20 13:16 UTC
